### ISSUE TITLE
macOS 12.0.1 or later 

### ISSUE THREAD

**Issue by b0gdanw** [Vaida12345/waifuExtension#7]
Hello,
is there a reason for requiring macOS 12.0.1 or later? Could it be compiled to run on Big Sur?
Regards,
Bogdan

**Comment by Vaida12345** [comment]
Actually there is not. I simply used the default configuration, which is the latest version. I will update [release 4.1.3](https://github.com/Vaida12345/waifuExtension/releases/tag/v4.1.3)

**Comment by Vaida12345** [comment]
That is because I used the latest `await / async` technology, which requires at least macOS 12.0. But before version 4.1.3 (latest one), this app was written without this technology, you can try to download the source code and compile yourself, and it should work on Big Sur (but not the ones before Big Sur, as SwiftUI was introduced with Big Sur).
As this software is only for me practicing my coding skills, I will not try to extend its compatibility. 

You can check out imxieyi's work [here](https://github.com/imxieyi/waifu2x-ios), which is also available on the App Store. It seems that he built his app with `UIKit` and `Catalyst`, so his app would work fine on [macOS Catalina](https://en.wikipedia.org/wiki/MacOS_Catalina). 
Also, you should use his app if you wish to have better performance for models expect for Waifu2x. As he used the CoreML, I simply used their packages.
